paginate = 40
defaultContentLanguage = 'ru'
showLanguageSelector = false
defaultContentLanguageInSubdir = false
baseURL = '/'

disableKinds = ["taxonomy","sitemap","RSS"]

[params]
[sitemap]
filename = '/sitemap.xml'


[outputs]
    home = ["HTML", "JSON"]

[languages]
[languages.ru]
  contentDir = 'content/ru'
  languageName = "RU"
  weight= 1
  title = "Северные горизонты"
  copyright = "Дмитрий Садоков"
  [languages.ru.params]
    keywords = "НКО, Северные горизонты, ООПТ, заповедник"
    subtitle = "НКО"
    owner = "Дмитрий Садоков"
    description = "НКО, Некоммерческая организация"
    flag = "ru.svg"

[languages.en]
  contentDir = 'content/en'
  languageName = "EN"
  weight= 2
  title = "Northern horizons"
  copyright = "Dmitrii Sadokov"
  [languages.en.params]
    keywords = "NPO, Protected areas, Northern horizons, conservation areas, nature reserve"
    subtitle = "NPO"
    owner = "Dmitrii Sadokov"
    description = "NPO, Autonomous non-profit organization"
    flag = "en.svg"

[languages.ru.menu]
  [[languages.ru.menu.main]]
        identifier = "home"
        name = "О нас "
        pageRef= "/"
        weight = 1
  [[languages.ru.menu.main]]
        identifier = "organization"
        name = "Организация"
        pageref= "/organization"
        weight = 4
  [[languages.ru.menu.main]]
        identifier = "team"
        name = "Команда"
        pageref= "/team"
        weight = 5
  [[languages.ru.menu.main]]
        identifier = "works"
        name = "Наша работа"
        pageRef= "/works"
        weight = 6
  [[languages.ru.menu.main]]
        identifier = "news"
        name = "Новости"
        pageRef= "/news"
        weight = 8
  [[languages.ru.menu.main]]
        identifier = "contacts"
        name = "Контакты"
        pageRef= "/contacts"
        weight = 9

[languages.en.menu]
  [[languages.en.menu.main]]
      identifier = "home"
        name = "Home"
        pageRef= "/"
        weight = 1
  [[languages.en.menu.main]]
        identifier = "organization"
        name = "Organization"
        pageref= "/organization"
        weight = 4
  [[languages.en.menu.main]]
        identifier = "team"
        name = "Team"
        pageref= "/team"
        weight = 5
  [[languages.en.menu.main]]
        identifier = "works"
        name = "Works"
        pageRef= "/works"
        weight = 6
  [[languages.en.menu.main]]
        identifier = "news"
        name = "News"
        pageRef= "/news"
        weight = 8
  [[languages.en.menu.main]]
        identifier = "contacts"
        name = "Contacts"
        pageRef= "/contacts"
        weight = 9

